const express = require('express');
const router = express.Router();
const controllers = require('../controllers/controllers');
router.use(express.json());
router.get('/books', controllers.getAllBooks);
router.get('/books/:id', controllers.getBookById);
router.post('/books', controllers.createBook);
router.put('/books/:id', controllers.updateBook);
router.delete('/books/:id', controllers.deleteBook);
module.exports = router;